== Neo4j Movies Application: 

Ứng dụng Neo4j Movies nhóm 5 (Môn Quản lý dữ liệu) thực hiện thông qua trang chủ Neo4j với link :
https://neo4j.com/developer/example-project/
Sau đó nhóm thực hiện deploy ứng dụng lên web app thông qua heroku https://www.heroku.com/

=== The Stack

Các components có trong Web Application:

* Application Type:         Python-Web Application
* Web framework:
  - sync: https://palletsprojects.com/p/flask/[Flask] (Micro-Webframework)
  - async: https://fastapi.tiangolo.com/[FastAPI] (Micro-Webframework)
* Neo4j Database Connector: https://github.com/neo4j/neo4j-python-driver[Neo4j Python Driver] for Cypher https://neo4j.com/developer/python[Docs]
* Database:                 Neo4j-Server (4.4 or newer) with multi-database
* Frontend:                 jquery, bootstrap, https://d3js.org/[d3.js]

Provision a database quickly with https://sandbox.neo4j.com/?usecase=movies[Neo4j Sandbox] or https://neo4j.com/cloud/aura/[Neo4j Aura].


=== Các bước cài đặt

Install Python 3.7-3.11.

Then get yourself set up with link:http://docs.python-guide.org/en/latest/dev/virtualenvs/[virtualenv] so we don't break any other Python stuff you have on your machine. After you've got that installed let's set up an environment for our app:

[source]
----
virtualenv neo4j-movies
source neo4j-movies/bin/activate
----

Bước tiếp theo cài đặt dependencies cho app with pip (or pip3 for python3):

sync:

[source]
----
pip install -r requirements-sync.txt
----

async:

[source]
----
pip install -r requirements-async.txt
----

=== Run locally

And finally let's start up a web server:

sync:

[source]
----
python movies_sync.py
# or python3 movies_sync.py

Running on http://127.0.0.1:8080/
----

async:

[source]
----
python movies_async.py
# or python3 movies_async.py

Running on http://127.0.0.1:8080/
----




